This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./Thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (171 entries accepted, 0 rejected).
Sorting entries....done (1348 comparisons).
Generating output file Thesis.acr....done (108 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
